### ISSUE TITLE
import langchain_community module error

### ISSUE THREAD

**Issue by zevorn** [JinghaoZhao/GPT-Code-Learner#13]
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing SupabaseVectorStore from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import SupabaseVectorStore

with new imports of:

>> from langchain_community.vectorstores import SupabaseVectorStore
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing TextLoader from langchain.document_loaders is deprecated. Please replace deprecated imports:

>> from langchain.document_loaders import TextLoader

with new imports of:

>> from langchain_community.document_loaders import TextLoader
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing PyPDFLoader from langchain.document_loaders is deprecated. Please replace deprecated imports:

>> from langchain.document_loaders import PyPDFLoader

with new imports of:

>> from langchain_community.document_loaders import PyPDFLoader
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/__init__.py:30: UserWarning: Importing OpenAI from langchain root module is no longer supported. Please use langchain_community.llms.OpenAI instead.
  warnings.warn(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/llms/__init__.py:549: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/langchain/chat_models/__init__.py:33: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/hupper/ipc.py", line 332, in spawn_main
    func(**kwargs)
  File "/home/zevorn/GPT-Code-Learner/gpt-python-env/lib/python3.12/site-packages/hupper/worker.py", line 286, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/home/zevorn/GPT-Code-Learner/code_learner.py", line 194, in main
    repo_link_btn = gr.Button("Analyze Code Repo").style(full_width=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Button' object has no attribute 'style'. Did you mean: 'scale'?
Press ENTER or change a file to reload.

**Comment by zevorn** [comment]
$ python --version
Python 3.12.4

(gpt-python-env) zevorn@ZEVORN-PC GPT-Code-Learner (main) $ pip list
Package                  Version
------------------------ -----------
aiofiles                 23.2.1
aiohappyeyeballs         2.4.0
aiohttp                  3.10.5
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.4.0
attrs                    24.2.0
beautifulsoup4           4.12.3
certifi                  2024.7.4
chardet                  5.2.0
charset-normalizer       3.3.2
click                    8.1.7
contourpy                1.2.1
cycler                   0.12.1
dataclasses-json         0.6.7
deprecation              2.1.0
distro                   1.9.0
faiss-cpu                1.8.0.post1
fastapi                  0.112.1
ffmpy                    0.4.0
filelock                 3.15.4
fonttools                4.53.1
frozenlist               1.4.1
fsspec                   2024.6.1
gotrue                   2.7.0
gradio                   4.41.0
gradio_client            1.3.0
greenlet                 3.0.3
h11                      0.14.0
h2                       4.1.0
hpack                    4.0.0
httpcore                 1.0.5
httpx                    0.27.0
huggingface-hub          0.24.6
hupper                   1.12.1
hyperframe               6.0.1
idna                     3.7
importlib_resources      6.4.3
Jinja2                   3.1.4
jiter                    0.5.0
joblib                   1.4.2
jsonpatch                1.33
jsonpointer              3.0.0
kiwisolver               1.4.5
langchain                0.2.14
langchain-community      0.2.12
langchain-core           0.2.33
langchain-text-splitters 0.2.2
langsmith                0.1.99
markdown-it-py           3.0.0
MarkupSafe               2.1.5
marshmallow              3.21.3
matplotlib               3.9.2
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.0.5
mypy-extensions          1.0.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
openai                   1.41.1
orjson                   3.10.7
packaging                24.1
pandas                   2.2.2
pillow                   10.4.0
pip                      24.0
postgrest                0.16.10
pydantic                 2.8.2
pydantic_core            2.20.1
pydub                    0.25.1
Pygments                 2.18.0
pyparsing                3.1.2
pypdf                    4.3.1
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
python-multipart         0.0.9
pytz                     2024.1
PyYAML                   6.0.2
realtime                 2.0.1
regex                    2024.7.24
requests                 2.32.3
rich                     13.7.1
ruff                     0.6.1
safetensors              0.4.4
scikit-learn             1.5.1
scipy                    1.14.0
semantic-version         2.10.0
sentence-transformers    3.0.1
setuptools               73.0.0
shellingham              1.5.4
six                      1.16.0
sniffio                  1.3.1
soupsieve                2.6
SQLAlchemy               2.0.32
starlette                0.38.2
storage3                 0.7.7
StrEnum                  0.4.15
supabase                 2.7.2
supafunc                 0.5.1
sympy                    1.13.2
tenacity                 8.5.0
termcolor                2.4.0
threadpoolctl            3.5.0
tiktoken                 0.7.0
tokenizers               0.19.1
tomlkit                  0.12.0
torch                    2.4.0
tqdm                     4.66.5
transformers             4.44.0
triton                   3.0.0
typer                    0.12.4
typing_extensions        4.12.2
typing-inspect           0.9.0
tzdata                   2024.1
urllib3                  2.2.2
uvicorn                  0.30.6
websockets               12.0
yarl                     1.9.4

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
